"""
Comprehensive Report Generator for Bridge Hydrology Agent
"""

from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime


class HydrologyReportGenerator:
    
    def __init__(self, catchment_data: dict, rainfall_data: dict, 
                 discharge_data: dict, scour_data: dict,
                 rainfall_analysis: dict = None):
        self.catchment = catchment_data
        self.rainfall = rainfall_data
        self.discharge = discharge_data
        self.scour = scour_data
        self.rainfall_analysis = rainfall_analysis or {}
        self.doc = Document()
    
    def _add_title_page(self):
        title = self.doc.add_heading('BRIDGE HYDROLOGY REPORT', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        subtitle = self.doc.add_paragraph('Hydrological and Hydraulic Analysis for Bridge Design')
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle.runs[0].font.size = Pt(14)
        
        self.doc.add_paragraph('\n\n')
        
        if self.catchment.get('bridge_name'):
            p = self.doc.add_paragraph()
            p.add_run('Bridge Name: ').bold = True
            p.add_run(str(self.catchment.get('bridge_name', 'N/A')))
        
        if self.catchment.get('chainage'):
            p = self.doc.add_paragraph()
            p.add_run('Chainage: ').bold = True
            p.add_run(str(self.catchment.get('chainage', 'N/A')))
        
        if self.catchment.get('latitude') and self.catchment.get('longitude'):
            p = self.doc.add_paragraph()
            p.add_run('Location: ').bold = True
            p.add_run(f"Lat: {self.catchment['latitude']:.6f}°, Lon: {self.catchment['longitude']:.6f}°")
        
        p = self.doc.add_paragraph()
        p.add_run('Report Date: ').bold = True
        p.add_run(datetime.now().strftime('%B %Y'))
        
        p = self.doc.add_paragraph()
        p.add_run('Generated by: ').bold = True
        p.add_run('Bridge Hydrology Agent v1.0')
        
        self.doc.add_page_break()
    
    def _add_catchment_characteristics(self):
        self.doc.add_heading('1. CATCHMENT CHARACTERISTICS', level=1)
        
        table = self.doc.add_table(rows=8, cols=2)
        table.style = 'Light Grid Accent 1'
        
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Parameter'
        hdr_cells[1].text = 'Value'
        
        data = [
            ('Catchment Area (A)', f"{self.catchment.get('A_km2', 0):.2f} km²"),
            ('Stream Length (L)', f"{self.catchment.get('L_km', 0):.2f} km"),
            ('Centroidal Length (Lc)', f"{self.catchment.get('Lc_km', 0):.2f} km"),
            ('Maximum Elevation (Hmax)', f"{self.catchment.get('Hmax_m', 0):.2f} m"),
            ('Minimum Elevation (Hmin)', f"{self.catchment.get('Hmin_m', 0):.2f} m"),
            ('Elevation Difference', f"{self.catchment.get('Hmax_m', 0) - self.catchment.get('Hmin_m', 0):.2f} m"),
            ('Average Slope (S)', f"{self.catchment.get('Slope', 0):.4f}")
        ]
        
        for i, (param, value) in enumerate(data, 1):
            row_cells = table.rows[i].cells
            row_cells[0].text = param
            row_cells[1].text = value
        
        self.doc.add_paragraph()
    
    def _add_rainfall_analysis(self):
        self.doc.add_heading('2. RAINFALL FREQUENCY ANALYSIS', level=1)
        
        self.doc.add_heading('2.1 Rainfall Statistics', level=2)
        
        if self.rainfall:
            table = self.doc.add_table(rows=6, cols=2)
            table.style = 'Light Grid Accent 1'
            
            stats_data = [
                ('Number of Years', str(self.rainfall.get('n_years', 0))),
                ('Mean Annual Maximum', f"{self.rainfall.get('mean', 0):.2f} mm"),
                ('Maximum Recorded', f"{self.rainfall.get('max', 0):.2f} mm"),
                ('Minimum Recorded', f"{self.rainfall.get('min', 0):.2f} mm"),
                ('Standard Deviation', f"{self.rainfall.get('std', 0):.2f} mm")
            ]
            
            for i, (param, value) in enumerate(stats_data):
                row_cells = table.rows[i].cells
                row_cells[0].text = param
                row_cells[1].text = value
        
        self.doc.add_heading('2.2 Goodness-of-Fit Tests', level=2)
        
        if self.rainfall_analysis.get('test_results'):
            table = self.doc.add_table(rows=1, cols=5)
            table.style = 'Light Grid Accent 1'
            
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'Distribution'
            hdr_cells[1].text = 'KS Statistic'
            hdr_cells[2].text = 'KS p-value'
            hdr_cells[3].text = 'Chi-Square'
            hdr_cells[4].text = 'Score'
            
            for dist_name, results in self.rainfall_analysis['test_results'].items():
                row_cells = table.add_row().cells
                row_cells[0].text = dist_name
                row_cells[1].text = f"{results.get('KS_statistic', 0):.4f}"
                row_cells[2].text = f"{results.get('KS_pvalue', 0):.4f}"
                
                chi2_val = results.get('Chi2_statistic')
                row_cells[3].text = f"{chi2_val:.4f}" if chi2_val is not None else "N/A"
                
                row_cells[4].text = f"{results.get('score', 0):.4f}"
            
            if self.rainfall_analysis.get('best_distribution'):
                p = self.doc.add_paragraph()
                p.add_run('\nBest Fitting Distribution: ').bold = True
                p.add_run(self.rainfall_analysis['best_distribution'])
        
        self.doc.add_heading('2.3 Return Period Rainfall Estimates', level=2)
        
        if self.rainfall_analysis.get('rainfall_estimates'):
            table = self.doc.add_table(rows=1, cols=2)
            table.style = 'Light Grid Accent 1'
            
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'Return Period (Years)'
            hdr_cells[1].text = 'Rainfall Depth (mm)'
            
            estimates = self.rainfall_analysis['rainfall_estimates']
            return_periods = ['2_year', '5_year', '10_year', '20_year', 
                            '50_year', '100_year', '200_year']
            
            period_labels = {
                '2_year': '2', '5_year': '5', '10_year': '10',
                '20_year': '20', '50_year': '50', '100_year': '100',
                '200_year': '200'
            }
            
            for period in return_periods:
                if period in estimates:
                    row_cells = table.add_row().cells
                    row_cells[0].text = period_labels[period]
                    row_cells[1].text = f"{estimates[period]:.2f}"
        
        self.doc.add_paragraph()
    
    def _add_discharge_analysis(self):
        self.doc.add_heading('3. PEAK DISCHARGE ANALYSIS', level=1)
        
        table = self.doc.add_table(rows=1, cols=2)
        table.style = 'Light Grid Accent 1'
        
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Method'
        hdr_cells[1].text = 'Peak Discharge (m³/s)'
        
        methods = [
            ('WECS Method', self.discharge.get('WECS_100yr', 0)),
            ('Modified Dickens Method', self.discharge.get('Dickens_100yr', 0)),
            ('B.D. Richards Method', self.discharge.get('Richards_100yr', 0)),
            ("Snyder's Method", self.discharge.get('Snyder_100yr', 0))
        ]
        
        for method_name, value in methods:
            if value:
                row_cells = table.add_row().cells
                row_cells[0].text = method_name
                row_cells[1].text = f"{value:.2f}"
        
        self.doc.add_heading('3.1 Adopted Design Discharge', level=2)
        
        if self.discharge.get('Adopted_Q100'):
            p = self.doc.add_paragraph()
            p.add_run('100-Year Peak Discharge (Q₁₀₀): ').bold = True
            p.add_run(f"{self.discharge['Adopted_Q100']:.2f} m³/s")
        
        if self.discharge.get('Design_Discharge'):
            p = self.doc.add_paragraph()
            p.add_run('Design Discharge (Qdesign): ').bold = True
            p.add_run(f"{self.discharge['Design_Discharge']:.2f} m³/s")
            p.add_run(' (including 10% climate change factor)')
        
        self.doc.add_paragraph()
    
    def _add_scour_calculation(self):
        self.doc.add_heading('4. SCOUR DEPTH CALCULATION', level=1)
        
        if not self.scour:
            self.doc.add_paragraph('Scour calculation data not available.')
            return
        
        self.doc.add_heading('4.1 Scour Parameters', level=2)
        
        if self.scour.get('parameters'):
            params = self.scour['parameters']
            table = self.doc.add_table(rows=6, cols=2)
            table.style = 'Light Grid Accent 1'
            
            param_data = [
                ('Design Discharge (Q)', f"{params.get('Q_design', 0):.2f} m³/s"),
                ('Bridge Length (L)', f"{params.get('L_bridge', 0):.2f} m"),
                ('Mean Bed Material Size (dmean)', f"{params.get('dmean_mm', 0):.2f} mm"),
                ('Silt Factor (Ksf)', f"{params.get('Ksf', 0):.2f}"),
                ("Blench's Zero Bed Factor (Fb)", f"{params.get('Blench_Fb', 0):.2f}")
            ]
            
            for i, (param, value) in enumerate(param_data):
                row_cells = table.rows[i].cells
                row_cells[0].text = param
                row_cells[1].text = value
        
        self.doc.add_heading('4.2 Mean Scour Calculation', level=2)
        
        table = self.doc.add_table(rows=1, cols=5)
        table.style = 'Light Grid Accent 1'
        
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Section'
        hdr_cells[1].text = "Lacey's (avg q)"
        hdr_cells[2].text = "Lacey's (max q)"
        hdr_cells[3].text = "Blench's"
        hdr_cells[4].text = 'Adopted'
        
        for section_name in ['upstream', 'existing']:
            if section_name in self.scour:
                scour_data = self.scour[section_name]['mean_scour']
                row_cells = table.add_row().cells
                row_cells[0].text = section_name.title()
                row_cells[1].text = f"{scour_data.get('D_lacey_avg', 0):.2f} m"
                row_cells[2].text = f"{scour_data.get('D_lacey_max', 0):.2f} m"
                row_cells[3].text = f"{scour_data.get('D_blench', 0):.2f} m"
                row_cells[4].text = f"{scour_data.get('D_adopted', 0):.2f} m"
        
        self.doc.add_heading('4.3 Pier and Abutment Scour', level=2)
        
        table = self.doc.add_table(rows=1, cols=3)
        table.style = 'Light Grid Accent 1'
        
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Parameter'
        hdr_cells[1].text = 'Upstream'
        hdr_cells[2].text = 'Existing'
        
        params = [
            'Adopted Mean Scour D (m)',
            'Scour Depth - Abutment (m)',
            'Scour Depth - Pier (m)',
            'Scour Level - Abutment (m)',
            'Scour Level - Pier (m)',
            'Minimum Soffit Level (m)'
        ]
        
        for param in params:
            row_cells = table.add_row().cells
            row_cells[0].text = param
            
            for section_name in ['upstream', 'existing']:
                if section_name in self.scour:
                    data = self.scour[section_name]
                    
                    if 'Mean Scour' in param:
                        value = data['mean_scour'].get('D_adopted', 0)
                    elif 'Abutment' in param and 'Depth' in param:
                        value = data['pier_abutment_scour'].get('D_abutment', 0)
                    elif 'Pier' in param and 'Depth' in param:
                        value = data['pier_abutment_scour'].get('D_pier', 0)
                    elif 'Abutment' in param and 'Level' in param:
                        value = data['scour_levels'].get('scour_level_abutment', 0)
                    elif 'Pier' in param and 'Level' in param:
                        value = data['scour_levels'].get('scour_level_pier', 0)
                    elif 'Soffit' in param:
                        value = data.get('min_soffit_level', 0)
                    else:
                        value = 0
                    
                    row_cells[1 if section_name == 'upstream' else 2].text = f"{value:.2f}"
        
        self.doc.add_paragraph()
    
    def generate_report(self, output_path: str) -> str:
        self._add_title_page()
        self._add_catchment_characteristics()
        self._add_rainfall_analysis()
        self._add_discharge_analysis()
        self._add_scour_calculation()
        
        self.doc.save(output_path)
        return output_path