"""
Comprehensive Report Generator for Bridge Hydrology Agent
Generates professional MS Word reports matching DoR Nepal standards
Includes IDF curve integration with plot and table
"""

from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
import pandas as pd
import os
from pathlib import Path


class HydrologyReportGenerator:
    """
    Generate comprehensive hydrology reports in MS Word format
    """
    
    def __init__(self, catchment_data: dict, rainfall_data: dict, 
                 discharge_data: dict, scour_data: dict,
                 rainfall_analysis: dict = None):
        """
        Initialize report generator
        
        Args:
            catchment_data: Catchment characteristics
            rainfall_data: Rainfall statistics
            discharge_data: Peak discharge results
            scour_data: Scour calculation results
            rainfall_analysis: Full rainfall analysis including IDF
        """
        self.catchment = catchment_data
        self.rainfall = rainfall_data
        self.discharge = discharge_data
        self.scour = scour_data
        self.rainfall_analysis = rainfall_analysis or {}
        self.doc = Document()
    
    def _add_title_page(self):
        """Add title page to report"""
        title = self.doc.add_heading('BRIDGE HYDROLOGY REPORT', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        subtitle = self.doc.add_paragraph('Hydrological and Hydraulic Analysis for Bridge Design')
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle.runs[0].font.size = Pt(14)
        
        self.doc.add_paragraph('\n\n')
        
        if self.catchment.get('bridge_name'):
            p = self.doc.add_paragraph()
            p.add_run('Bridge Name: ').bold = True
            p.add_run(str(self.catchment.get('bridge_name', 'N/A')))
        
        if self.catchment.get('chainage'):
            p = self.doc.add_paragraph()
            p.add_run('Chainage: ').bold = True
            p.add_run(str(self.catchment.get('chainage', 'N/A')))
        
        if self.catchment.get('latitude') and self.catchment.get('longitude'):
            p = self.doc.add_paragraph()
            p.add_run('Location: ').bold = True
            p.add_run(f"Lat: {self.catchment['latitude']:.6f}°, Lon: {self.catchment['longitude']:.6f}°")
        
        p = self.doc.add_paragraph()
        p.add_run('Report Date: ').bold = True
        p.add_run(datetime.now().strftime('%B %Y'))
        
        p = self.doc.add_paragraph()
        p.add_run('Generated by: ').bold = True
        p.add_run('Bridge Hydrology Agent v1.0')
        
        self.doc.add_page_break()
    
    def _add_catchment_characteristics(self):
        """Add catchment characteristics section"""
        self.doc.add_heading('1. CATCHMENT CHARACTERISTICS', level=1)
        
        table = self.doc.add_table(rows=8, cols=2)
        table.style = 'Light Grid Accent 1'
        
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Parameter'
        hdr_cells[1].text = 'Value'
        
        data = [
            ('Catchment Area (A)', f"{self.catchment.get('A_km2', 0):.2f} km²"),
            ('Stream Length (L)', f"{self.catchment.get('L_km', 0):.2f} km"),
            ('Centroidal Length (Lc)', f"{self.catchment.get('Lc_km', 0):.2f} km"),
            ('Maximum Elevation (Hmax)', f"{self.catchment.get('Hmax_m', 0):.2f} m"),
            ('Minimum Elevation (Hmin)', f"{self.catchment.get('Hmin_m', 0):.2f} m"),
            ('Elevation Difference', f"{self.catchment.get('Hmax_m', 0) - self.catchment.get('Hmin_m', 0):.2f} m"),
            ('Average Slope (S)', f"{self.catchment.get('Slope', 0):.4f}")
        ]
        
        for i, (param, value) in enumerate(data, 1):
            row_cells = table.rows[i].cells
            row_cells[0].text = param
            row_cells[1].text = value
        
        self.doc.add_paragraph()
    
    def _add_rainfall_analysis(self):
        """Add rainfall frequency analysis section"""
        self.doc.add_heading('2. RAINFALL FREQUENCY ANALYSIS', level=1)
        
        self.doc.add_heading('2.1 Rainfall Statistics', level=2)
        
        if self.rainfall:
            table = self.doc.add_table(rows=6, cols=2)
            table.style = 'Light Grid Accent 1'
            
            stats_data = [
                ('Number of Years', str(self.rainfall.get('n_years', 0))),
                ('Mean Annual Maximum', f"{self.rainfall.get('mean', 0):.2f} mm"),
                ('Maximum Recorded', f"{self.rainfall.get('max', 0):.2f} mm"),
                ('Minimum Recorded', f"{self.rainfall.get('min', 0):.2f} mm"),
                ('Standard Deviation', f"{self.rainfall.get('std', 0):.2f} mm")
            ]
            
            for i, (param, value) in enumerate(stats_data):
                row_cells = table.rows[i].cells
                row_cells[0].text = param
                row_cells[1].text = value
        
        self.doc.add_heading('2.2 Goodness-of-Fit Tests', level=2)
        
        if self.rainfall_analysis.get('test_results'):
            table = self.doc.add_table(rows=1, cols=5)
            table.style = 'Light Grid Accent 1'
            
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'Distribution'
            hdr_cells[1].text = 'KS Statistic'
            hdr_cells[2].text = 'KS p-value'
            hdr_cells[3].text = 'Chi-Square'
            hdr_cells[4].text = 'Score'
            
            for dist_name, results in self.rainfall_analysis['test_results'].items():
                row_cells = table.add_row().cells
                row_cells[0].text = dist_name
                row_cells[1].text = f"{results.get('KS_statistic', 0):.4f}"
                row_cells[2].text = f"{results.get('KS_pvalue', 0):.4f}"
                
                chi2_val = results.get('Chi2_statistic')
                row_cells[3].text = f"{chi2_val:.4f}" if chi2_val is not None else "N/A"
                
                row_cells[4].text = f"{results.get('score', 0):.4f}"
            
            if self.rainfall_analysis.get('best_distribution'):
                p = self.doc.add_paragraph()
                p.add_run('\nBest Fitting Distribution: ').bold = True
                p.add_run(self.rainfall_analysis['best_distribution'])
        
        self.doc.add_heading('2.3 Return Period Rainfall Estimates', level=2)
        
        if self.rainfall_analysis.get('rainfall_estimates'):
            table = self.doc.add_table(rows=1, cols=2)
            table.style = 'Light Grid Accent 1'
            
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'Return Period (Years)'
            hdr_cells[1].text = 'Rainfall Depth (mm)'
            
            estimates = self.rainfall_analysis['rainfall_estimates']
            return_periods = ['2_year', '5_year', '10_year', '20_year', 
                            '50_year', '100_year', '200_year']
            
            period_labels = {
                '2_year': '2', '5_year': '5', '10_year': '10',
                '20_year': '20', '50_year': '50', '100_year': '100',
                '200_year': '200'
            }
            
            for period in return_periods:
                if period in estimates:
                    row_cells = table.add_row().cells
                    row_cells[0].text = period_labels[period]
                    row_cells[1].text = f"{estimates[period]:.2f}"
        
        self.doc.add_paragraph()
    
    def _add_idf_analysis(self):
        """Add IDF analysis section with robust image handling"""
        self.doc.add_heading('2.4 IDF (Intensity-Duration-Frequency) Analysis', level=2)
        
        # Add IDF plot if available
        idf_plot_path = self.rainfall_analysis.get('idf_plot_path')
        
        print(f"\n=== IDF Plot Debug ===")
        print(f"Plot path: {idf_plot_path}")
        print(f"Plot path type: {type(idf_plot_path)}")
        
        if idf_plot_path:
            # Convert to string if it's a Path object
            idf_plot_path = str(idf_plot_path)
            
            print(f"File exists: {os.path.exists(idf_plot_path)}")
            print(f"File size: {os.path.getsize(idf_plot_path) if os.path.exists(idf_plot_path) else 0} bytes")
            print(f"Current directory: {os.getcwd()}")
            
            if os.path.exists(idf_plot_path):
                try:
                    # Add the picture with error handling
                    self.doc.add_picture(idf_plot_path, width=Inches(6.0))
                    self.doc.add_paragraph()
                    print(f"✅ IDF plot added to document")
                    
                    # Add caption - FIXED: Pass text directly to add_paragraph()
                    caption = self.doc.add_paragraph("Figure 2.1: IDF (Intensity-Duration-Frequency) Curves")
                    caption.style = 'Caption'
                    print(f"✅ Caption added")
                    
                except Exception as e:
                    print(f"❌ Error adding picture: {e}")
                    import traceback
                    traceback.print_exc()
                    
                    # Add placeholder text
                    placeholder = self.doc.add_paragraph()
                    placeholder.add_run(f"[IDF Plot: {idf_plot_path}]").italic = True
            else:
                print(f"⚠️ Plot file not found at: {idf_plot_path}")
                
                # Try alternative paths
                alt_paths = [
                    os.path.basename(idf_plot_path),  # Just filename
                    f'data/rainfall/idf_curve.png',
                    f'./data/rainfall/idf_curve.png',
                    idf_plot_path.replace('.jpg', '.png'),  # Try PNG if JPG failed
                ]
                
                for alt_path in alt_paths:
                    if os.path.exists(alt_path):
                        try:
                            self.doc.add_picture(alt_path, width=Inches(6.0))
                            self.doc.add_paragraph()
                            print(f"✅ IDF plot added using alternative path: {alt_path}")
                            break
                        except Exception as e:
                            print(f"❌ Alternative path failed: {alt_path} - {e}")
                else:
                    # No alternative worked
                    placeholder = self.doc.add_paragraph()
                    placeholder.add_run("[IDF Plot not available - file not found]").italic = True
        else:
            print("⚠️ No IDF plot path found")
            placeholder = self.doc.add_paragraph()
            placeholder.add_run("[IDF Plot not generated]").italic = True
        
        # Add IDF table
        if self.rainfall_analysis.get('idf_data'):
            self.doc.add_heading('2.4.1 Rainfall Intensity (mm/hr)', level=3)
            
            idf_data = self.rainfall_analysis['idf_data']
            
            try:
                # Get unique durations and return periods
                duration_labels = idf_data.get('Duration_Label', {})
                return_periods_data = idf_data.get('Return_Period', {})
                intensity_data = idf_data.get('Intensity_mm_hr', {})
                
                # Get unique values
                if duration_labels:
                    durations = sorted(set(duration_labels.values()), 
                                      key=lambda x: ['15 min', '30 min', '1 hr', '2 hr', '6 hr', '12 hr', '24 hr'].index(x) if x in ['15 min', '30 min', '1 hr', '2 hr', '6 hr', '12 hr', '24 hr'] else 99)
                else:
                    durations = ['15 min', '30 min', '1 hr', '2 hr', '6 hr', '12 hr', '24 hr']
                
                if return_periods_data:
                    return_periods = sorted(set(return_periods_data.values()))
                else:
                    return_periods = [2, 5, 10, 50, 100, 200]
                
                # Create table
                table = self.doc.add_table(rows=len(durations) + 1, cols=len(return_periods) + 1)
                table.style = 'Light Grid Accent 1'
                
                # Header row
                hdr_cells = table.rows[0].cells
                hdr_cells[0].text = 'Duration'
                for j, rp in enumerate(return_periods):
                    hdr_cells[j + 1].text = f'{rp}-year'
                
                # Data rows
                for i, duration in enumerate(durations):
                    row_cells = table.rows[i + 1].cells
                    row_cells[0].text = str(duration)
                    
                    for j, rp in enumerate(return_periods):
                        try:
                            intensity_value = 0.0
                            for idx in range(len(duration_labels)):
                                if duration_labels.get(idx, '') == duration and return_periods_data.get(idx, 0) == rp:
                                    intensity_value = intensity_data.get(idx, 0.0)
                                    break
                            
                            row_cells[j + 1].text = f"{float(intensity_value):.2f}"
                            
                        except (KeyError, TypeError, ValueError) as e:
                            row_cells[j + 1].text = "0.00"
                
                print(f"✅ IDF table added successfully")
                
            except Exception as e:
                print(f"❌ Error creating IDF table: {e}")
                import traceback
                traceback.print_exc()
        
        print(f"=== End IDF Analysis ===\n")
        
        self.doc.add_paragraph()
    
    def _add_discharge_analysis(self):
        """Add peak discharge analysis section"""
        self.doc.add_heading('3. PEAK DISCHARGE ANALYSIS', level=1)
        
        table = self.doc.add_table(rows=1, cols=2)
        table.style = 'Light Grid Accent 1'
        
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Method'
        hdr_cells[1].text = 'Peak Discharge (m³/s)'
        
        methods = [
            ('WECS Method', self.discharge.get('WECS_100yr', 0)),
            ('Modified Dickens Method', self.discharge.get('Dickens_100yr', 0)),
            ('B.D. Richards Method', self.discharge.get('Richards_100yr', 0)),
            ("Snyder's Method", self.discharge.get('Snyder_100yr', 0))
        ]
        
        for method_name, value in methods:
            if value:
                row_cells = table.add_row().cells
                row_cells[0].text = method_name
                row_cells[1].text = f"{value:.2f}"
        
        self.doc.add_heading('3.1 Adopted Design Discharge', level=2)
        
        if self.discharge.get('Adopted_Q100'):
            p = self.doc.add_paragraph()
            p.add_run('100-Year Peak Discharge (Q₁₀₀): ').bold = True
            p.add_run(f"{self.discharge['Adopted_Q100']:.2f} m³/s")
        
        if self.discharge.get('Design_Discharge'):
            p = self.doc.add_paragraph()
            p.add_run('Design Discharge (Qdesign): ').bold = True
            p.add_run(f"{self.discharge['Design_Discharge']:.2f} m³/s")
            p.add_run(' (including 10% climate change factor)')
        
        self.doc.add_paragraph()
    
    def _add_scour_calculation(self):
        """Add scour calculation section"""
        self.doc.add_heading('4. SCOUR DEPTH CALCULATION', level=1)
        
        if not self.scour:
            self.doc.add_paragraph('Scour calculation data not available.')
            return
        
        self.doc.add_heading('4.1 Scour Parameters', level=2)
        
        if self.scour.get('parameters'):
            params = self.scour['parameters']
            table = self.doc.add_table(rows=10, cols=2)
            table.style = 'Light Grid Accent 1'
            
            param_data = [
                ('Design Discharge (Q)', f"{params.get('Q_design', 0):.2f} m³/s"),
                ('Bridge Length (L)', f"{params.get('L_bridge', 0):.2f} m"),
                ('Mean Bed Material Size (dmean)', f"{params.get('dmean_mm', 0):.2f} mm"),
                ('Silt Factor (Ksf)', f"{params.get('Ksf', 0):.2f}"),
                ("Blench's Zero Bed Factor (Fb)", f"{params.get('Blench_Fb', 0):.2f}"),
                ('Average Discharge Intensity (q_avg)', f"{params.get('q_avg', 0):.3f} m²/s"),
                ('Maximum Discharge Intensity (q_max)', f"{params.get('q_max', 0):.3f} m²/s"),
                ('Water Surface Elevation (HFL/WSE)', f"{params.get('HFL', 0):.2f} m")
            ]
            
            for i, (param, value) in enumerate(param_data):
                row_cells = table.rows[i].cells
                row_cells[0].text = param
                row_cells[1].text = value
        
        self.doc.add_heading('4.2 Mean Scour Calculation', level=2)
        
        table = self.doc.add_table(rows=1, cols=2)
        table.style = 'Light Grid Accent 1'
        
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Method'
        hdr_cells[1].text = 'Scour Depth (m)'
        
        if 'bridge_section' in self.scour:
            scour_data = self.scour['bridge_section']['mean_scour']
            
            methods = [
                ("Lacey's (avg q)", scour_data.get('D_lacey_avg', 0)),
                ("Lacey's (max q)", scour_data.get('D_lacey_max', 0)),
                ("Blench's", scour_data.get('D_blench', 0)),
                ('Adopted', scour_data.get('D_adopted', 0))
            ]
            
            for method_name, value in methods:
                row_cells = table.add_row().cells
                row_cells[0].text = method_name
                row_cells[1].text = f"{value:.2f} m"
        
        self.doc.add_heading('4.3 Pier and Abutment Scour', level=2)
        
        table = self.doc.add_table(rows=1, cols=2)
        table.style = 'Light Grid Accent 1'
        
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Parameter'
        hdr_cells[1].text = 'Value'
        
        if 'bridge_section' in self.scour:
            data = self.scour['bridge_section']
            
            params = [
                ('Adopted Mean Scour D (m)', data['mean_scour'].get('D_adopted', 0)),
                ('Scour Depth - Abutment (m)', data['pier_abutment_scour'].get('D_abutment', 0)),
                ('Scour Depth - Pier (m)', data['pier_abutment_scour'].get('D_pier', 0)),
                ('Scour Level - Abutment (m)', data['scour_levels'].get('scour_level_abutment', 0)),
                ('Scour Level - Pier (m)', data['scour_levels'].get('scour_level_pier', 0)),
                ('Minimum Soffit Level (m)', data.get('min_soffit_level', 0)),
                ('Water Surface Elevation (HFL/WSE)', data.get('HFL', 0))
            ]
            
            for param_name, value in params:
                row_cells = table.add_row().cells
                row_cells[0].text = param_name
                row_cells[1].text = f"{value:.2f}"
        
        self.doc.add_paragraph()
    
    def generate_report(self, output_path: str) -> str:
        """
        Generate complete hydrology report
        
        Args:
            output_path: Path to save the report
            
        Returns:
            Path to saved report
        """
        print("\n=== Generating Report ===")
        print(f"Output path: {output_path}")
        print(f"rainfall_analysis keys: {list(self.rainfall_analysis.keys())}")
        print(f"idf_plot_path in rainfall_analysis: {self.rainfall_analysis.get('idf_plot_path')}")
        
        self._add_title_page()
        self._add_catchment_characteristics()
        self._add_rainfall_analysis()
        self._add_idf_analysis()
        self._add_discharge_analysis()
        self._add_scour_calculation()
        
        self.doc.save(output_path)
        print(f"✅ Report saved to: {output_path}")
        print(f"=== Report Generation Complete ===\n")
        return output_path