# -*- coding: utf-8 -*-
"""
Created on Sun Mar 15 13:24:52 2026

@author: user
"""

"""
Comprehensive Report Generator for Bridge Hydrology Agent
Generates professional MS Word reports matching DoR Nepal standards
"""

import pandas as pd
import numpy as np
from pathlib import Path
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
from docx.oxml.ns import qn
import plotly.graph_objects as go
import plotly.io as pio
from PIL import Image
import io

class HydrologyReportGenerator:
    """
    Generates comprehensive hydrology reports in MS Word format
    Based on Ratu Bridge Hydrology Report (DoR Nepal)
    """
    
    def __init__(self, catchment_data: dict, rainfall_data: dict, 
                 discharge_data: dict, scour_data: dict,
                 rainfall_analysis: dict = None):
        """
        Initialize report generator with all analysis results
        
        Args:
            catchment_data: Dictionary with catchment characteristics
            rainfall_data: Dictionary with rainfall statistics
            discharge_data: Dictionary with discharge calculations
            scour_data: Dictionary with scour calculations
            rainfall_analysis: Dictionary with frequency analysis results
        """
        self.catchment = catchment_data
        self.rainfall = rainfall_data
        self.discharge = discharge_data
        self.scour = scour_data
        self.rainfall_analysis = rainfall_analysis or {}
        self.doc = Document()
        
    def _add_title_page(self):
        """Add professional title page"""
        # Title
        title = self.doc.add_heading('BRIDGE HYDROLOGY REPORT', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Subtitle
        subtitle = self.doc.add_paragraph('Hydrological and Hydraulic Analysis for Bridge Design')
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle.runs[0].font.size = Pt(14)
        
        self.doc.add_paragraph('\n\n')
        
        # Project details
        if self.catchment.get('bridge_name'):
            p = self.doc.add_paragraph()
            p.add_run('Bridge Name: ').bold = True
            p.add_run(str(self.catchment.get('bridge_name', 'N/A')))
        
        if self.catchment.get('chainage'):
            p = self.doc.add_paragraph()
            p.add_run('Chainage: ').bold = True
            p.add_run(str(self.catchment.get('chainage', 'N/A')))
        
        if self.catchment.get('latitude') and self.catchment.get('longitude'):
            p = self.doc.add_paragraph()
            p.add_run('Location: ').bold = True
            p.add_run(f"Lat: {self.catchment['latitude']:.6f}°, "
                     f"Lon: {self.catchment['longitude']:.6f}°")
        
        # Date
        p = self.doc.add_paragraph()
        p.add_run('Report Date: ').bold = True
        p.add_run(datetime.now().strftime('%B %Y'))
        
        p = self.doc.add_paragraph()
        p.add_run('Generated by: ').bold = True
        p.add_run('Bridge Hydrology Agent v1.0')
        
        self.doc.add_page_break()
    
    def _add_table_of_contents(self):
        """Add table of contents"""
        self.doc.add_heading('TABLE OF CONTENTS', level=1)
        
        toc_items = [
            '1. Executive Summary',
            '2. Catchment Characteristics',
            '3. Rainfall Data Analysis',
            '   3.1 Rainfall Statistics',
            '   3.2 Frequency Distribution Analysis',
            '   3.3 Goodness-of-Fit Tests',
            '   3.4 Return Period Rainfall Estimates',
            '4. Peak Discharge Analysis',
            '   4.1 Method Comparison',
            '   4.2 Adopted Design Discharge',
            '5. Scour Depth Calculation',
            '   5.1 Scour Parameters',
            '   5.2 Mean Scour Calculation',
            '   5.3 Pier and Abutment Scour',
            '6. Conclusions and Recommendations',
            '7. Appendices'
        ]
        
        for item in toc_items:
            self.doc.add_paragraph(item)
        
        self.doc.add_page_break()
    
    def _add_executive_summary(self):
        """Add executive summary section"""
        self.doc.add_heading('1. EXECUTIVE SUMMARY', level=1)
        
        summary = self.doc.add_paragraph()
        summary.add_run('This report presents the hydrological analysis for bridge design ')
        summary.add_run('based on Department of Roads (DoR) Nepal guidelines. ')
        summary.add_run('The analysis includes:\n\n')
        
        # Key findings
        self.doc.add_heading('Key Findings:', level=2)
        
        # Catchment
        p = self.doc.add_paragraph(style='List Bullet')
        p.add_run('Catchment Area: ').bold = True
        p.add_run(f"{self.catchment.get('A_km2', 0):.2f} km²")
        
        # Rainfall
        if self.rainfall_analysis.get('R100yr'):
            p = self.doc.add_paragraph(style='List Bullet')
            p.add_run('100-year Rainfall (R₁₀₀): ').bold = True
            p.add_run(f"{self.rainfall_analysis['R100yr']:.2f} mm")
            if self.rainfall_analysis.get('best_distribution'):
                p.add_run(f" ({self.rainfall_analysis['best_distribution']} distribution)")
        
        # Discharge
        if self.discharge.get('Design_Discharge'):
            p = self.doc.add_paragraph(style='List Bullet')
            p.add_run('Design Discharge (Qdesign): ').bold = True
            p.add_run(f"{self.discharge['Design_Discharge']:.2f} m³/s")
            p.add_run(" (including 10% climate change factor)")
        
        # Scour
        if self.scour:
            p = self.doc.add_paragraph(style='List Bullet')
            p.add_run('Maximum Scour Depth: ').bold = True
            if self.scour.get('upstream'):
                p.add_run(f"{self.scour['upstream']['mean_scour']['D_adopted']:.2f} m (Upstream), ")
            if self.scour.get('existing'):
                p.add_run(f"{self.scour['existing']['mean_scour']['D_adopted']:.2f} m (Existing)")
        
        self.doc.add_paragraph()
    
    def _add_catchment_characteristics(self):
        """Add catchment characteristics section (Table 1 format)"""
        self.doc.add_heading('2. CATCHMENT CHARACTERISTICS', level=1)
        
        self.doc.add_paragraph('The following catchment parameters were used in the analysis:')
        
        # Create table
        table = self.doc.add_table(rows=7, cols=2)
        table.style = 'Light Grid Accent 1'
        
        # Header
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Parameter'
        hdr_cells[1].text = 'Value'
        
        # Data
        data = [
            ('Catchment Area (A)', f"{self.catchment.get('A_km2', 0):.2f} km²"),
            ('Stream Length (L)', f"{self.catchment.get('L_km', 0):.2f} km"),
            ('Centroidal Length (Lc)', f"{self.catchment.get('Lc_km', 0):.2f} km"),
            ('Maximum Elevation (Hmax)', f"{self.catchment.get('Hmax_m', 0):.2f} m"),
            ('Minimum Elevation (Hmin)', f"{self.catchment.get('Hmin_m', 0):.2f} m"),
            ('Elevation Difference', f"{self.catchment.get('Hmax_m', 0) - self.catchment.get('Hmin_m', 0):.2f} m"),
            ('Average Slope (S)', f"{self.catchment.get('Slope', 0):.4f}")
        ]
        
        for i, (param, value) in enumerate(data, 1):
            row_cells = table.rows[i].cells
            row_cells[0].text = param
            row_cells[1].text = value
        
        # Location info
        self.doc.add_paragraph('\nBridge Location:')
        p = self.doc.add_paragraph(style='List Bullet')
        p.add_run('Latitude: ').bold = True
        p.add_run(f"{self.catchment.get('latitude', 0):.6f}° N")
        
        p = self.doc.add_paragraph(style='List Bullet')
        p.add_run('Longitude: ').bold = True
        p.add_run(f"{self.catchment.get('longitude', 0):.6f}° E")
        
        self.doc.add_paragraph()
    
    def _add_rainfall_analysis(self):
        """Add comprehensive rainfall analysis section"""
        self.doc.add_heading('3. RAINFALL DATA ANALYSIS', level=1)
        
        # 3.1 Rainfall Statistics
        self.doc.add_heading('3.1 Rainfall Statistics', level=2)
        
        if self.rainfall:
            table = self.doc.add_table(rows=5, cols=2)
            table.style = 'Light Grid Accent 1'
            
            stats_data = [
                ('Number of Years', str(self.rainfall.get('n_years', 0))),
                ('Mean Annual Maximum', f"{self.rainfall.get('mean', 0):.2f} mm"),
                ('Maximum Recorded', f"{self.rainfall.get('max', 0):.2f} mm"),
                ('Minimum Recorded', f"{self.rainfall.get('min', 0):.2f} mm"),
                ('Standard Deviation', f"{self.rainfall.get('std', 0):.2f} mm")
            ]
            
            for i, (param, value) in enumerate(stats_data):
                row_cells = table.rows[i].cells
                row_cells[0].text = param
                row_cells[1].text = value
        
        # 3.2 Frequency Distribution Analysis
        self.doc.add_heading('3.2 Frequency Distribution Analysis', level=2)
        
        if self.rainfall_analysis.get('test_results'):
            self.doc.add_paragraph('Goodness-of-fit tests were performed for multiple distributions:')
            
            # Create table for test results
            table = self.doc.add_table(rows=1, cols=5)
            table.style = 'Light Grid Accent 1'
            
            # Header
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'Distribution'
            hdr_cells[1].text = 'KS Statistic'
            hdr_cells[2].text = 'KS p-value'
            hdr_cells[3].text = 'Chi-Square'
            hdr_cells[4].text = 'Score'
            
            # Data
            for dist_name, results in self.rainfall_analysis['test_results'].items():
                row_cells = table.add_row().cells
                row_cells[0].text = dist_name
                row_cells[1].text = f"{results.get('KS_statistic', 0):.4f}"
                row_cells[2].text = f"{results.get('KS_pvalue', 0):.4f}"
                row_cells[3].text = f"{results.get('Chi2_statistic', 0):.4f}"
                row_cells[4].text = f"{results.get('score', 0):.4f}"
            
            # Best distribution
            if self.rainfall_analysis.get('best_distribution'):
                p = self.doc.add_paragraph()
                p.add_run('\nBest Fitting Distribution: ').bold = True
                p.add_run(self.rainfall_analysis['best_distribution'])
        
        # 3.3 Return Period Rainfall Estimates
        self.doc.add_heading('3.3 Return Period Rainfall Estimates', level=2)
        
        if self.rainfall_analysis.get('rainfall_estimates'):
            table = self.doc.add_table(rows=1, cols=2)
            table.style = 'Light Grid Accent 1'
            
            # Header
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'Return Period (Years)'
            hdr_cells[1].text = 'Rainfall Depth (mm)'
            
            # Data
            estimates = self.rainfall_analysis['rainfall_estimates']
            return_periods = ['2_year', '5_year', '10_year', '20_year', 
                            '50_year', '100_year', '200_year']
            
            period_labels = {
                '2_year': '2',
                '5_year': '5',
                '10_year': '10',
                '20_year': '20',
                '50_year': '50',
                '100_year': '100',
                '200_year': '200'
            }
            
            for period in return_periods:
                if period in estimates:
                    row_cells = table.add_row().cells
                    row_cells[0].text = period_labels[period]
                    row_cells[1].text = f"{estimates[period]:.2f}"
        
        self.doc.add_paragraph()
    
    def _add_discharge_analysis(self):
        """Add peak discharge analysis section"""
        self.doc.add_heading('4. PEAK DISCHARGE ANALYSIS', level=1)
        
        # 4.1 Method Comparison (Table 5 format)
        self.doc.add_heading('4.1 Method Comparison', level=2)
        
        table = self.doc.add_table(rows=1, cols=2)
        table.style = 'Light Grid Accent 1'
        
        # Header
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Method'
        hdr_cells[1].text = 'Peak Discharge (m³/s)'
        
        # Add all methods
        methods = [
            ('WECS Method', self.discharge.get('WECS_100yr', 0)),
            ('Modified Dickens Method', self.discharge.get('Dickens_100yr', 0)),
            ('B.D. Richards Method', self.discharge.get('Richards_100yr', 0)),
            ("Snyder's Method", self.discharge.get('Snyder_100yr', 0))
        ]
        
        for method_name, value in methods:
            if value:
                row_cells = table.add_row().cells
                row_cells[0].text = method_name
                row_cells[1].text = f"{value:.2f}"
        
        # 4.2 Adopted Design Discharge
        self.doc.add_heading('4.2 Adopted Design Discharge', level=2)
        
        if self.discharge.get('Adopted_Q100'):
            p = self.doc.add_paragraph()
            p.add_run('100-Year Peak Discharge (Q₁₀₀): ').bold = True
            p.add_run(f"{self.discharge['Adopted_Q100']:.2f} m³/s")
        
        if self.discharge.get('Design_Discharge'):
            p = self.doc.add_paragraph()
            p.add_run('Design Discharge (Qdesign): ').bold = True
            p.add_run(f"{self.discharge['Design_Discharge']:.2f} m³/s")
            p.add_run(' (including 10% climate change factor)')
        
        self.doc.add_paragraph()
    
    def _add_scour_calculation(self):
        """Add scour calculation section (Tables 7, 8, 9 format)"""
        self.doc.add_heading('5. SCOUR DEPTH CALCULATION', level=1)
        
        if not self.scour:
            self.doc.add_paragraph('Scour calculation data not available.')
            return
        
        # 5.1 Scour Parameters (Table 7)
        self.doc.add_heading('5.1 Scour Parameters', level=2)
        
        if self.scour.get('parameters'):
            params = self.scour['parameters']
            table = self.doc.add_table(rows=5, cols=2)
            table.style = 'Light Grid Accent 1'
            
            param_data = [
                ('Design Discharge (Q)', f"{params.get('Q_design', 0):.2f} m³/s"),
                ('Bridge Length (L)', f"{params.get('L_bridge', 0):.2f} m"),
                ('Mean Bed Material Size (dmean)', f"{params.get('dmean_mm', 0):.2f} mm"),
                ('Silt Factor (Ksf)', f"{params.get('Ksf', 0):.2f}"),
                ("Blench's Zero Bed Factor (Fb)", f"{params.get('Blench_Fb', 0):.2f}")
            ]
            
            for i, (param, value) in enumerate(param_data):
                row_cells = table.rows[i].cells
                row_cells[0].text = param
                row_cells[1].text = value
        
        # 5.2 Mean Scour Calculation (Table 8)
        self.doc.add_heading('5.2 Mean Scour Calculation', level=2)
        
        table = self.doc.add_table(rows=1, cols=5)
        table.style = 'Light Grid Accent 1'
        
        # Header
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Section'
        hdr_cells[1].text = "Lacey's (avg q)"
        hdr_cells[2].text = "Lacey's (max q)"
        hdr_cells[3].text = "Blench's"
        hdr_cells[4].text = 'Adopted'
        
        # Add upstream and existing sections
        for section_name in ['upstream', 'existing']:
            if section_name in self.scour:
                scour_data = self.scour[section_name]['mean_scour']
                row_cells = table.add_row().cells
                row_cells[0].text = section_name.title()
                row_cells[1].text = f"{scour_data.get('D_lacey_avg', 0):.2f} m"
                row_cells[2].text = f"{scour_data.get('D_lacey_max', 0):.2f} m"
                row_cells[3].text = f"{scour_data.get('D_blench', 0):.2f} m"
                row_cells[4].text = f"{scour_data.get('D_adopted', 0):.2f} m"
        
        # 5.3 Pier and Abutment Scour (Table 9)
        self.doc.add_heading('5.3 Pier and Abutment Scour', level=2)
        
        table = self.doc.add_table(rows=1, cols=3)
        table.style = 'Light Grid Accent 1'
        
        # Header
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Parameter'
        hdr_cells[1].text = 'Upstream'
        hdr_cells[2].text = 'Existing'
        
        # Data
        params = [
            'Adopted Mean Scour D (m)',
            'Scour Depth - Abutment (m)',
            'Scour Depth - Pier (m)',
            'Scour Level - Abutment (m)',
            'Scour Level - Pier (m)',
            'Minimum Soffit Level (m)'
        ]
        
        for param in params:
            row_cells = table.add_row().cells
            row_cells[0].text = param
            
            for section_name in ['upstream', 'existing']:
                if section_name in self.scour:
                    data = self.scour[section_name]
                    
                    if 'Mean Scour' in param:
                        value = data['mean_scour'].get('D_adopted', 0)
                    elif 'Abutment' in param and 'Depth' in param:
                        value = data['pier_abutment_scour'].get('D_abutment', 0)
                    elif 'Pier' in param and 'Depth' in param:
                        value = data['pier_abutment_scour'].get('D_pier', 0)
                    elif 'Abutment' in param and 'Level' in param:
                        value = data['scour_levels'].get('scour_level_abutment', 0)
                    elif 'Pier' in param and 'Level' in param:
                        value = data['scour_levels'].get('scour_level_pier', 0)
                    elif 'Soffit' in param:
                        value = data.get('min_soffit_level', 0)
                    else:
                        value = 0
                    
                    row_cells[1 if section_name == 'upstream' else 2].text = f"{value:.2f}"
        
        self.doc.add_paragraph()
    
    def _add_conclusions(self):
        """Add conclusions and recommendations"""
        self.doc.add_heading('6. CONCLUSIONS AND RECOMMENDATIONS', level=1)
        
        self.doc.add_heading('Conclusions:', level=2)
        
        conclusions = [
            f"The catchment area for the bridge site is {self.catchment.get('A_km2', 0):.2f} km².",
        ]
        
        if self.rainfall_analysis.get('R100yr'):
            conclusions.append(
                f"The 100-year rainfall depth is {self.rainfall_analysis['R100yr']:.2f} mm "
                f"based on {self.rainfall_analysis.get('best_distribution', 'frequency analysis')} distribution."
            )
        
        if self.discharge.get('Design_Discharge'):
            conclusions.append(
                f"The design discharge for 100-year return period is "
                f"{self.discharge['Design_Discharge']:.2f} m³/s including climate change factor."
            )
        
        if self.scour:
            if self.scour.get('upstream'):
                conclusions.append(
                    f"The maximum scour depth at upstream section is "
                    f"{self.scour['upstream']['mean_scour']['D_adopted']:.2f} m."
                )
            if self.scour.get('existing'):
                conclusions.append(
                    f"The maximum scour depth at existing bridge section is "
                    f"{self.scour['existing']['mean_scour']['D_adopted']:.2f} m."
                )
        
        for conclusion in conclusions:
            p = self.doc.add_paragraph(style='List Number')
            p.add_run(conclusion)
        
        # Recommendations
        self.doc.add_heading('Recommendations:', level=2)
        
        recommendations = [
            'Foundation levels should be provided below the calculated scour levels with adequate factor of safety.',
            'Regular monitoring of river morphology is recommended during monsoon seasons.',
            'The design discharge should be reviewed if significant land use changes occur in the catchment.',
            'Hydraulic model (HEC-RAS) should be calibrated with field observations.'
        ]
        
        for rec in recommendations:
            p = self.doc.add_paragraph(style='List Number')
            p.add_run(rec)
        
        self.doc.add_paragraph()
    
    def _add_appendices(self):
        """Add appendices section"""
        self.doc.add_heading('7. APPENDICES', level=1)
        
        self.doc.add_heading('Appendix A: Methodology', level=2)
        
        self.doc.add_paragraph("""
The following methods were used in this hydrological analysis:

1. **WECS Method**: Regional flood frequency analysis based on catchment area.

2. **Modified Dickens Method**: Empirical formula considering catchment area and 
   return period with regional coefficients.

3. **B.D. Richards Method**: Time of concentration-based approach with areal 
   reduction factor and rainfall intensity-duration relationships.

4. **Snyder's Method**: Synthetic unit hydrograph method using regional parameters 
   Ct (basin lag coefficient) and Cp (peak discharge coefficient).

5. **Scour Calculation**: 
   - Lacey's formula for regime channels
   - Blench Zero Bed Factor approach
   - Pier scour = 2.0 × mean scour depth
   - Abutment scour = 1.27 × mean scour depth
""")
        
        self.doc.add_heading('Appendix B: References', level=2)
        
        references = [
            'Department of Roads Nepal. "Hydrologic and Hydraulic Analysis of Ratu River at Bridge Site."',
            'WECS. "Regional Flood Frequency Analysis for Nepal."',
            'Lacey, G. (1939). "Regime Flow in Incoherent Alluvium."',
            'Blench, T. (1957). "Regime Behaviour of Canals and Rivers."',
            'Snyder, C.T. (1938). "A Generalized Equation for Unit Hydrographs."',
            'IRC:5-2015. "Standard Specifications and Code of Practice for Road Bridges."'
        ]
        
        for ref in references:
            p = self.doc.add_paragraph(style='List Bullet')
            p.add_run(ref)
    
    def generate_report(self, output_path: str) -> str:
        """
        Generate complete hydrology report and save to DOCX file
        
        Args:
            output_path: Path to save the DOCX file
            
        Returns:
            Path to the generated report
        """
        # Add all sections
        self._add_title_page()
        self._add_table_of_contents()
        self._add_executive_summary()
        self._add_catchment_characteristics()
        self._add_rainfall_analysis()
        self._add_discharge_analysis()
        self._add_scour_calculation()
        self._add_conclusions()
        self._add_appendices()
        
        # Save document
        self.doc.save(output_path)
        
        return output_path